### ISSUE TITLE
Bevy v0.13

### ISSUE THREAD

**Issue by UkoeHB** [projectharmonia/bevy_replicon#185]
- Now that [generations start at 1](https://github.com/bevyengine/bevy/pull/9907), we will need to update entity serialization for bevy v0.13.
- The new [EntityMapper](https://github.com/bevyengine/bevy/pull/11428) trait means we can deprecate `MapNetworkEntities` and `Mapper`.

**Comment by Shatur** [comment]
[Conditions should be regular systems](https://github.com/bevyengine/bevy/pull/11316) if possible for consistency with Bevy.

**Comment by dgsantana** [comment]
I made a PR #198 to update to bevy 0.13.
