### ISSUE TITLE
Why drain mapped client events?

### ISSUE THREAD

**Issue by CHATALOT1** [projectharmonia/bevy_replicon#195]
On [this line](https://github.com/projectharmonia/bevy_replicon/blob/master/src/network_event/client_event.rs#L202), events are drained before being mapped and sent. I believe this is done for efficiency's sake (to avoid having to clone the events before mapping) but it is inconsistent with the behaviour of the other default systems for network events. Non-mapped client events are not drained (only read), and neither are server events. This may lead to confusing behaviour.
In my case, it meant that my system intended to run on the client and read events of a type added with `App::add_mapped_client_event` never found any, as they had been drained to send to the server.

I would like to make the behaviour consistent across the default network event sending systems, with my preference being that events are not drained in any of them. The current functionality of the sending system for mapped events may be more efficient, but maybe could be provided under a different function (e.g. `App::add_mapped_client_event_drained`).

I am willing to create a pull request implementing these changes myself, just thought I would make this issue first in case maintainers disagree with this direction.

**Comment by Shatur** [comment]
Yes, I did it to avoid requiring `Clone`.
But I agree with the suggestion. Feel free to open a PR.
