### ISSUE TITLE
Use a single system for events

### ISSUE THREAD

**Issue by Shatur** [projectharmonia/bevy_replicon#245]
Instead of registering multiple systems, we can use a single system by using custom functions (similar to what we do for components).
This will make the public API simpler and more efficient.
Bevy did a similar optimization recently: https://github.com/bevyengine/bevy/pull/12936 and we can benefit from the provided `EventRegistry`.

**Comment by notmd** [comment]
I will try to take this. And will try to fix the 1 channel per event as well. This is really a foot gun for us and also limits the amount of events the app can have.

**Comment by Shatur** [comment]
> I will try to take this.

Great, I will be happy to review it. Let me know if you have any questions about the implementation.

> And will try to fix the 1 channel per event as well. 

We need control over reliability guarantee. So maybe 3 channels for each event type.
