### ISSUE TITLE
More modularity

### ISSUE THREAD

**Issue by MOZGIII** [projectharmonia/bevy_replicon#27]
Hello! Awesome project, looks very much like what I'd like to use (or implement myself), except I need to use a different networking layer for my game.

I figured I could simply use the `replication_core` - but that is also dependent on renet. Would be great if this project was working around simply a trait anyone could implement as a bring-your-own networking layer kind of thing.

In addition, the project is currently structured as a single crate. I suspect I will have issues with building it to wasm for the web due to the dependencies on Send/Sync stuff and other things that don't work in wasm - so even if I won't use them I suspect it won't build.

---

Would you consider restructuring the code in such a way that:
1. It allows pluggable networking backends, with renet implemented out of the box as one of them.
2. The core replication logic is usable without the networking at all, as a self-contained package. The networking layer can work on top of the replication mechanisms, by driving the inner workings however needed.
3. The core logic (and possibly the networking interface itself) can be usable in wasm - so it can run in the browser.

The rationale for (2) in addition to (1) is that in the browser environment, it could be possible that the data exchange is not even done via the network in common sense - maybe it uses message posting or some other odd way (i.e. serializing the exchanges via HTTP requests and SSE responses). In these situations, it would be hard to implement a trait that looks something like a networking API, but it would be possible to drive the core logic via the data obtained "somehow".

**Comment by Shatur** [comment]
Hi! Thanks.
I thought about exactly this. The project originated from the networking from my game, that's why it coupled with Renet. My plan was to introduce a trait and have a separate `bevy_replicon_renet` crate.
Although Renet also recently introduced different transports... So I currently not sure which path to take. I think having different transports on Renet side is easier to maintain. However it currently doesn't support wasm, so someone need to write this transport layer.

**Comment by MOZGIII** [comment]
I suggest going with replicon's own traits - it will definitely be beneficial, and it will allow the implementation to be more expressive.

In my game I have a layer of traits for networking (that describes what my game needs). I have a couple of networking implementations that are directly using the natively available APIs that the platform offers, and there is another implementation that is itself based on an abstraction layer around the networking (this thing actually: https://github.com/MOZGIII/xwebtransport). I can highly recommend this approach, as it is very interesting to compare the implementations and investigate the architectural designs that would've been otherwise undiscovered.

---

On the renet side - it would be cool to add WebTransport as a backing transport, and it would probably be easy since it should only need its unreliable datagrams part, as renet has its own implementations for the rest to be built on top. The only downside of WebTransport for that, in particular, is that it is sometimes implemented on top of HTTP/2 which will make unreliable datagrams actually (unwantedly) reliable (and thus slow).

**Comment by Shatur** [comment]
Makes sense... I also had similar suggestions in Discord.

I currently focused on my game, but if you want to tackle this issue - I will be happy to review and merge it. Also feel free to ask any questions about the architecture.

**Comment by MOZGIII** [comment]
Maybe a bit later. I could do it, but it seems like a lot of work, and this would be a pretty deep dive - so I'm not sure I have the bandwidth for that now.

**Comment by Shatur** [comment]
Understandable. But it's not that coupled with Renet really. All is needed is to create traits for clients and servers and make plugins generic. And then create a crate for renet that implements this trait.

> In these situations, it would be hard to implement a trait that looks something like a networking API, but it would be possible to drive the core logic via the data obtained "somehow".

But not sure about this... This crate need only message sending, receiving and list of client IDs.
