### ISSUE TITLE
Despawn failure should not panic

### ISSUE THREAD

**Issue by UkoeHB** [projectharmonia/bevy_replicon#355]
Reported on discord. If the server replicates an entity despawn but the entity was manually despawned on the client, replicon currently panics. It should not need to panic.

**Comment by mirsella** [comment]
```
thread 'main' panicked at /home/mirsella/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_replicon-0.28.4/src/client.rs:429:45:
Entity Entity { index: 175, generation: 1 } does not exist
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_replicon::client::ClientPlugin::receive_replication`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```
this correspond to
```rs
        // SAFETY: access is unique and used to obtain `EntityMut`, which is just a wrapper over `UnsafeEntityCell`.
        let mut client_entity: EntityMut =
            unsafe { world_cell.world_mut().entity_mut(client_entity).into() };
```
its `entity_mut` which panic as stated in its doc.
is now here:
https://github.com/projectharmonia/bevy_replicon/blob/0efa80723af57cac220cbf9ddbe30c08251b7220/src/core/replication/deferred_entity.rs#L23

**Comment by Shatur** [comment]
>  If the server replicates an entity despawn but the entity was manually despawned on the client, replicon currently panics.

Hm... That's actually not the case, we very explicitly handle it:
https://github.com/projectharmonia/bevy_replicon/blob/0efa80723af57cac220cbf9ddbe30c08251b7220/src/client.rs#L394-L405

> its entity_mut which panic as stated in its doc.

It looks like this occurs during removals and changes. If the entity is already despawned on the client but the server sends replication for it, we panic. It is a user mistake; they should not despawn a replicated entity from the server. Should we replace this with a warning instead?

**Comment by UkoeHB** [comment]
> Should we replace this with a warning instead?

Yeah this seems better. Less aggressive

**Comment by Shatur** [comment]
Maybe it should be error instead of warning? :thinking:

**Comment by UkoeHB** [comment]
> Maybe it should be error instead of warning? 🤔

I personally like to do `error` when there is a catastrophic problem of some kind (usually a library bug), and warn if the user caused some problem that is bad but not catastrophic.

**Comment by Shatur** [comment]
I looked into it, and to avoid a panic, I will need to skip the deserialization of the invalid entity. But I don't know size of components.
I can serialize the components size instead of their count, but that would make the packing worse. I think I'll keep it as a panic for now to prioritize the efficiency.
