### ISSUE TITLE
Expose replication groups at runtime

### ISSUE THREAD

**Issue by tyoeer** [projectharmonia/bevy_replicon#362]
I'm writing a little debugging UI that lists entities that should replicate, for which I am trying to track matching replication groups. However, I haven't found a way to get the registered replication groups. (Except from copy-paste-edit from the source code, which is error-prone, and doesn't generalise)

From my look at the source code, this should only require making `bevy_replicon::core::replication_rules::ReplicationRules` and `bevy_replicon::core::replication_registry::FnsInfo::component_id()` public.

**Comment by Shatur** [comment]
I'm open to making them public. Feel free to submit a PR!
