### ISSUE TITLE
Support for custom renet transports

### ISSUE THREAD

**Issue by jonastar** [projectharmonia/bevy_replicon#61]
I'm currently trying to get this to work with a couple of custom renet transports I wrote for running a client inside wasm.

After some debugging, I found out that the client systems will only `.run_if(client_connected())` where the client_connected() run condition is from renet, that run condition will only return `true` if the built-in renet client transport is connected and not any custom ones.

**Comment by Shatur** [comment]
Yes, the plugin currently coupled with `Netcode` transport. It's because renet doesn't export any generic check if client is connected and does not have any labels for its system:
https://github.com/lifescapegame/bevy_replicon/blob/9560d62ad891293ed3f0d33ac2d3b59b4006059e/src/client.rs#L30

I asked the author about it several times. If you working on a custom transport, maybe you could add the necessary API to renet to allow third-party crates to abstract over transport?

**Comment by Shatur** [comment]
> We could configure this in the client plugins (default to renet's client_connected()).

If I remember correctly, Renet have `client_connected` condition for each transport (steam and netcode). I would ask the author to expose `is_connected` to `RenetClient`.

**Comment by Shatur** [comment]
> I think we need to abstract away the transport plugin.

Yes, that's what I suggesting! I just think that it would be nicer to do it on Renet side.

> Maybe a good long-term solution would be adding a transport trait to bevy_replicon that encapsulate the backend API needed.

Yes, this would solve #27. But I still considering it...

**Comment by jonastar** [comment]
> I asked the author about it https://github.com/lucaspoffo/renet/pull/97#issuecomment-1643404698, but have no response. If you working on a custom transport, maybe you could add the necessary API to renet to allow third-party crates to abstract over transport?

Possibly yeah, but this seems like a relatively complex thing for a new contributor, but we'll see depending on what you decide to do here.

**Comment by Shatur** [comment]
Opened https://github.com/lucaspoffo/renet/issues/115

**Comment by jonastar** [comment]
Been experimenting more and just swapping out the `client_connected` calls with `resource_exists::<RenetClient>()` seems to work, not sure if there are any other side effects though

**Comment by jonastar** [comment]
Depends on how it's used I suppose, but there's also a [is_disconnected](https://docs.rs/renet/latest/renet/struct.RenetClient.html#method.is_disconnected) function on RenetClient

**Comment by Shatur** [comment]
> not sure if there are any other side effects though

It's fine, you can use this as a temporary solution :)
